### ISSUE TITLE
'window.twittr' is not a sufficient check

### ISSUE THREAD

**Issue by tammomueller** [capaj/react-tweet-embed#19]
When using other libraries from twitter such as [Twitter Text](https://github.com/twitter/twitter-text) the check that is currently in place to check the presence of the widget.js script fails as the twttr object is present.

Using `if (!(window.twttr && window.twttr.ready)) {` solves this bug.

**Comment by rwieruch** [comment]
Thanks for providing this Component. Helped me a lot to get up and running quickly with embedded tweets. Since I have error tracking for my web application, I see sometimes `Cannot read property 'ready' of undefined`. I tracked it down to my embedded tweets and I guess the fix lies in the library itself.

**Comment by capaj** [comment]
@rwieruch wooot you're using this? that is awesome. Will add the check in 1.1.0 as @tammomueller suggested.

**Comment by rwieruch** [comment]
I am using it for https://roadtoreact.com 😃  Thanks again for helping out here! 👍
